// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pzzdkztkwvbshtfhjkke.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6emRrenRrd3Zic2h0Zmhqa2tlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4NzEwNDksImV4cCI6MjA1OTQ0NzA0OX0.Hd02d9wvMu4PtKpA8GmKccaJtjHCt_zQiJJshXCyTpQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);